name: uji1
on: 
  workflow_dispatch:
   inputs:
     auth:
        description: 'TOKEN'
        required: true
        default: 'tempelkan kode token di sini'
  
jobs: 
 Mulai-Kerja: 
    runs-on: ubuntu-22.04
    timeout-minutes: 358
  
    steps: 
    - uses: actions/checkout@v3
    - name: build1
      continue-on-error: true 
      run: sudo bash data.sh
    - name: build2
      continue-on-error: true 
      run: sudo bash server.sh
    - name: build3
      continue-on-error: true 
      run: sudo bash timer.sh
