name: uji
on: 
  workflow_dispatch:
   inputs:
     auth:
        description: 'TOKEN'
        required: true
        default: 'tempelkan kode token di sini'
  
jobs: 
 Mulai-Kerja: 
    runs-on: ubuntu-22.04
    timeout-minutes: 358
  
    steps:
    - uses: actions/checkout@v3
    - name: kode1
      continue-on-error: true 
      run: |
          sudo bash tcp.sh
          ./ngrok authtoken ${{ github.event.inputs.auth }}
          ./ngrok tcp 5000 >/dev/null 2>&1 >/dev/null &
    - name: build1
      run: sudo bash data.sh
    - name: build2
      run: sudo bash server.sh
    - name: build3
      continue-on-error: true 
      run: sudo bash timer.sh
